version: '3.8'

services:
  backend:
    image: howardha/ktb-team20-fe:latest
    container_name: ktb-team20-frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - ktb-team20-frontend

networks:
  ktb-team20-frontend:
    driver: bridge