version: '3.8'

services:
  backend:
    image: howardha/ktb-team20-be:latest
    container_name: ktb-team20-backend
    ports:
      - "5001:5001"
      - "5002:5002"
    restart: always
    env_file:
      - .env
    networks:
      - ktb-team20-backend

networks:
  ktb-team20-backend:
    driver: bridge